# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_login_register', '0001_initial'),
        ('app3_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_posts', models.ManyToManyField(related_name='posts', to='app1_login_register.User')),
            ],
        ),
    ]
